language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "7"
before_script:
  - npm install -g gulp
# script: grunt
# Run test script, depending on istanbul install
#  - "test -n $(npm -ps ls istanbul) || npm test"
#  - "test -z $(npm -ps ls istanbul) || npm run-script test-travis"

#after_script:
#  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"